### ISSUE TITLE
Issues during global destruction

### ISSUE THREAD

**Issue by atoomic** [cpanel/Test-MockFile#106]
Noticed this issue while running some tests, this is coming from `t/medium/build-tools-generate_perlcriticrc_sync.t` 
need to check if already fixed or not

```
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 464 during global destruction.
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 465 during global destruction.
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 464 during global destruction.
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 465 during global destruction.
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 464 during global destruction.
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 465 during global destruction.
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 464 during global destruction.
( STDERR )  job  1    Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/532/lib/perl5/cpanel_lib/Test/MockFile.pm line 465 during global destruction.
```

**Comment by xsawyerx** [comment]
@atoomic, Is this what you fixed in #150?

**Comment by atoomic** [comment]
yes this is fixing that described issue, but I'm concerned that this is still a problem globally
but until we do not have a way to reproduce it, let's close this issue for now
